auth:
  registry.hub.docker.com:
    username: zdf188
    password: zdf131777
images:
  k8s.gcr.io/metrics-server/metrics-server: zdf188/metrics-server
  k8s.gcr.io/ingress-nginx/controller: zdf188/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: zdf188/git-sync
  gcr.io/kaniko-project/executor:debug,latest: zdf188/kaniko-executor
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: zdf188/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: zdf188/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: zdf188/prometheus-adapter

