auth:
  registry.hub.docker.com:
    username: zdf188
    password: zdf131777
images:
  k8s.gcr.io/metrics-server/metrics-server: willdockerhub/metrics-server
  k8s.gcr.io/ingress-nginx/controller: willdockerhub/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: willdockerhub/git-sync
  gcr.io/kaniko-project/executor:debug,latest: willdockerhub/kaniko-executor
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: willdockerhub/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: willdockerhub/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: willdockerhub/prometheus-adapter
